spring.application.name=date-app

# 1. DB 접속 정보 (친구의 DB 서버)
spring.datasource.url=jdbc:mysql://192.168.45.240:3306/datecourse
spring.datasource.username=root
spring.datasource.password=8208
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. JPA 설정
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# 3. 구글 맵 API 키 (오타 방지용)
google.maps.api.key=AIzaSyBmGU328t9PHtw6mTaB5AtnoHpdL1om0Gw

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
